### PR TITLE
Added controller game start, toggable fps counter and fixed cheats

### LINKED ISSUE #64: "Skip" despawns in endgame
When pushing it inside the podium

### LINKED ISSUE #71: Butttons clickable with controller

### PR DESCRIPTION
**Pull request by Bram-Boris**
# Description

Cheating with controller 
- Not possible, you can now always use the keyboard bindings

Start a game with the controller:
- From main menu to lobby.
- From lobby to actual gamestart.

fixes #64 
fixes #71 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Included 1 or more screenshots
- [x] Code is const correct

### CODE REVIEW

File: lib/systems/cheat_system.cpp [hunk 1]
```diff
@@ -29,6 +29,7 @@ void CheatSystem::update(double deltatime) {
 
     // Next scene
     if(input.checkInput(player_id, PlayerInput::SKIP_LEVEL)) {
+        std::cout << "test" << std::endl;
```
Comment (MarkMeer) [inline lib/systems/cheat_system.cpp]: This can be removed 🤶

**Review by MarkMeer — APPROVED** [review]
Nice🔥

**Review by LuukSantegoeds — APPROVED** [review]
